### ISSUE TITLE
Warnings in Julia v0.4

### ISSUE THREAD

**Issue by juliohm** [andrewcooke/IntModN.jl#3]
Thank you for this package.

Could you please fix a few warnings:

> WARNING: module IntModN should explicitly import / from Base
> WARNING: Base.Uint is deprecated, use UInt instead.
>   likely near /home/juliohm/.julia/v0.4/IntModN/src/IntModN.jl:109
> WARNING: module IntModN should explicitly import == from Base
> WARNING: module IntModN should explicitly import <= from Base
> WARNING: module IntModN should explicitly import < from Base
> WARNING: module IntModN should explicitly import - from Base
> WARNING: module IntModN should explicitly import ^ from Base
> WARNING: module IntModN should explicitly import + from Base
> WARNING: module IntModN should explicitly import \* from Base
> WARNING: module IntModN should explicitly import & from Base
> WARNING: module IntModN should explicitly import | from Base
> WARNING: module IntModN should explicitly import $ from Base
> WARNING: module IntModN should explicitly import % from Base
> WARNING: module IntModN should explicitly import << from Base
> WARNING: module IntModN should explicitly import >>> from Base
> WARNING: using IntModN.factor in module Main conflicts with an existing identifier.

**Comment by andrewcooke** [comment]
i'll try sometime this week.

**Comment by andrewcooke** [comment]
ok, so this isn't so simple.  the code in git doesn't have these warnings, so you can use that.  however, some tests for the code in git fail - i think i was working on trying to simplify the structure at some point and never finished.

i don't have time to complete that work, so your best bet may be to branch the code at the last release and fix the issues yourself.

i will add a note to the front page indicating that the package has issues and i don't have time to maintain it right now.  sorry.

**Comment by juliohm** [comment]
I will close the issue since the project is not maintained. Thanks.
